agent/urls.py
from django.conf.urls import url
from django.views.generic import UpdateView
from views import *
from models import Vendor
from forms import VendorForm

urlpatterns = [
    url(r'^all/$', VendorListView.as_view(), name="all"),
    url(r'^all/json$', VendorJSONListView.as_view(), name="all-json"),
    url(r'^new/$', VendorCreate.as_view(), name="new"),
    url(r'^details/(?P<pk>\d+)/$', VendorDetailView.as_view(), name="detail"),
    url(r'^update/(?P<pk>\d+)/$', UpdateView.as_view(
        model=Vendor,
        form_class=VendorForm,
        template_name='agent/vendor_create_form.html',
        success_url='/vendors/all/'
        ), name="update"),
]

fanaider/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^vendors/', include('agent.urls', namespace='vendors')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

agent/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

from PIL import Image

class Agent(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.name

class Shop(models.Model):
    location = models.CharField(max_length=100)
    agent = models.ForeignKey(Agent)

    def __unicode__(self):
        return self.agent.name + " " + self.location

class ShopAssistant(models.Model):
    user = models.OneToOneField(User)
    shop = models.OneToOneField(Shop)

    def __unicode__(self):
        return self.user.first_name + " " + self.user.last_name \
            + " --  " + self.shop.agent.name + " (" + self.shop.location + ")"


class Vendor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name  = models.CharField(max_length=100)
    phone      = models.CharField(max_length=50)
    hometown   = models.CharField(max_length=100)
    date_of_birth = models.DateField(blank=True, null=True)

    guarantor  = models.CharField(max_length=100)
    guarantor_location = models.CharField(max_length=100, default="Accra")
    relation   = models.CharField(max_length=100)
    guarantor_phone = models.CharField(max_length=50)

    profile = models.ImageField(upload_to="profiles/", \
                                blank=True, default="profiles/default.png")
    shop = models.ForeignKey(Shop, null=True)

    def __unicode__(self):
        return self.first_name + " " + self.last_name

    def get_average_sales(self):
        avg_list = self.vendorbooking_set\
            .filter(closed=True).aggregate(Avg('total')).values()
        if avg_list[0] == None:
            avg_list[0] = 0.0
        return avg_list[0]

agent/forms.py
from django import forms
from models import Vendor
from agent.models import ShopAssistant


class VendorForm(forms.ModelForm):

    class Meta:
        model = Vendor
        fields = ['first_name', 'last_name', 'phone', 'hometown',
                  'guarantor', 'relation', 'guarantor_phone',
                  'guarantor_location', 'date_of_birth', 'profile']

agent/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from forms import VendorForm
from models import Vendor, ShopAssistant
from sales.models import VendorBooking

from django.db.models import Avg, Sum
import datetime

class VendorListView(LoginRequiredMixin, ListView):
    model = Vendor
    template_name = "agent/all_vendors.html"

    def get_context_data(self, **kwargs):
        context = super(VendorListView, self).get_context_data(**kwargs)
        rank_dict = {}
        total_dict = {}
        for index, vendor in enumerate(self.get_queryset()):
            rank_dict[vendor.pk]=index + 1
            total_dict[vendor.pk]=vendor.total

        context['rank'] = rank_dict
        context['total'] = total_dict
        return context

    def get_queryset(self):

        rank = Vendor.objects\
            .annotate(total=Sum('vendorbooking__total'))\
            .order_by('-total')
        try:
            shop_assistant = ShopAssistant.objects.\
                get(user=self.request.user)
            rank = rank.filter(shop=shop_assistant.shop)

        except ShopAssistant.DoesNotExist:
            print "Admin Login"


        return rank

class VendorDetailView(LoginRequiredMixin, DetailView):
    template_name = 'agent/vendor_details.html'
    model = Vendor
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super(VendorDetailView, self).get_context_data(**kwargs)
        sales = VendorBooking.objects.filter(vendor=self.object)
        context['sales'] = sales
        print sales
        return context

class VendorJSONListView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        from django.core.serializers import serialize
        vendors = Vendor.objects.all()
        return HttpResponse(serialize('json', vendors))


class VendorCreate(LoginRequiredMixin, CreateView):
    form_class = VendorForm
    template_name = "agent/vendor_create_form.html"

    def form_valid(self, form):
        print form
        self.object = form.save()

        if 'shopassistants' in [group.name for group in self.request.user.groups.all()]:
            self.object.agent = self.request.user.shopassistant.shop.agent
            self.object.shop = self.request.user.shopassistant.shop

        elif u'agents' in [group.name for group in self.request.user.groups.all()]:
            self.object.agent = self.request.user.agent

        self.object.save()
        return HttpResponseRedirect(reverse('vendors:all'))

    def form_invalid(self, form):
        print form
        return super(VendorCreate, self).form_invalid(form)

templates/agent/all_vendors.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% load dict_filter %}
{% load list_filter %}
{% block subnav %}
{% include "vendors_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
		    <p class="section-title">All Vendors <span class="badge vendor-total">0</span></p>
	    </div>
	    <div class="section-data vendors-container">
		    <div class="vendor-list row">
			    {% for vendor in object_list %}
			    <div class="col-xsm-6 col-sm-6 col-md-4 col-lg-3 flex-container">
				    <div class="thumbnail">
				        <a href="/vendors/details/{{vendor.pk}}">
					    <img class="vendor-profile" src="{{vendor.profile.url}}" alt="">
					    <div class="caption">
						    
						    <p class="vendor-name"><span class="fa fa-user"></span> {{vendor.first_name|title}} {{vendor.last_name|title}}</p>
						    <p class="vendor-phone"><span class="fa fa-phone"></span> {{vendor.phone}}</p>
					    </div>
				        </a>
					<div class="card-divider"></div>
						<div class="sales-info-wrapper">
							<div class="col-xs-6">
								<p class="vendor-rank text-nowrap"><span class="fa fa-trophy"></span> {{rank|get_item:vendor.pk}} </p>
							</div>
							<div class="col-xs-6">
								<p class="vendor-month-total"><span class="fa fa-shopping-cart"></span>{% if total|get_item:vendor.pk == None %} {{0.00|floatformat:2}}{% else %} {{total|get_item:vendor.pk|floatformat:2|intcomma}}{% endif %}</p>
							</div>
						</div>
				     </div>
			     </div>
			    {% empty %}
			    <h3>There are no vendors registered</h3>
			    {% endfor %}
		    </div>
            </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#vendors-link").addClass("active");
		$("#vendor-all").addClass("active");
		$(".badge.vendor-total").html({{object_list|length}});
	})
</script>
{% endblock %}

templates/agent/vendor_create_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block subnav %}
{% include "vendors_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">New Vendor</p>
	    </div>
	    <div class="section-data">
		   {% if purchase_form.errors or form.errors %}
		   <div class="alert-danger">The data you provided has errors. Please correct them.</div>
		   {% endif %}
        <form action="#" method="post" role="form" enctype="multipart/form-data">
		{%csrf_token%}
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_first_name">First Name:</label>
			      {% render_field form.first_name class+="form-control" %}
			      {% if form.first_name.errors %}
			          {% for error in form.first_name.errors %}
				      <div class="alert-danger">{{error}}</div>
				  <script>$("#id_first_name").addClass("has-error")</script>
				  {% endfor%}
			      {% endif %}
			</div>
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_last_name">Last Name:</label>
			      {% render_field form.last_name class+="form-control" %}
			      {% if form.last_name.errors %}
			          {% for error in form.last_name.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_last_name").addClass("has-error")</script>
			      {% endif %}
			
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_phone">Phone:</label>
			      {% render_field form.phone class+="form-control" %}
			      {% if form.phone.errors %}
			          {% for error in form.phone.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_phone").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_hometown">Hometown:</label>
			      {% render_field form.hometown class+="form-control" %}
			      {% if form.hometown.errors %}
				  {% for error in form.hometown.errors %}
				      <div class="alert-danger">{{error}}</div>
				  <script>$("#id_hometown").addClass("has-error")</script>
				  {% endfor%}
			      {% endif %}
			</div>
		</div>
		<div class="row">
			<div class="form-group col-md-6">
			      <label class="control-label" for="id_profile">Passport Picture:</label>
			      {% render_field form.profile class+="form-control" %}
			      {% if form.profile.errors %}
				  {% for error in form.profile.errors %}
				      <div class="alert-danger">{{error}}</div>
				  <script>$("#id_profile").addClass("has-error")</script>
				  {% endfor%}
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_date_of_birth">Date of Birth:</label>
			      {% render_field form.date_of_birth class+="form-control datepicker" %}
			      {% if form.date_of_birth.errors %}
				  {% for error in form.date_of_birth.errors %}
				      <div class="alert-danger">{{error}}</div>
				  <script>$("#id_date_of_birth").addClass("has-error")</script>
				  {% endfor%}
			      {% endif %}
			</div>
		</div>
		<hr class=padding-bottom-10>
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_guarantor">Guarantor:</label>
			      {% render_field form.guarantor class+="form-control" %}
			      {% if form.guarantor.errors %}
			          {% for error in form.guarantor.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_guarantor").addClass("has-error")</script>
			      {% endif %}
			
			</div>
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_guarantor_location">Guarantor Location:</label>
			      {% render_field form.guarantor_location class+="form-control" %}
			      {% if form.guarantor_location.errors %}
			          {% for error in form.guarantor_location.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_guarantor_location").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_guarantor_phone">Guarantor Phone:</label>
			      {% render_field form.guarantor_phone class+="form-control" %}
			      {% if form.guarantor_phone.errors %}
			          {% for error in form.guarantor_phone.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_phone").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_relation">Relation:</label>
			      {% render_field form.relation class+="form-control" %}
			      {% if form.relation.errors %}
			          {% for error in form.relation.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_relation").addClass("has-error")</script>
			      {% endif %}
			</div>
		</div>
	<div class=row>
	    <div class="col-md-4"></div> <!-- spacer-->
	    <div class="col-md-5"></div> <!-- spacer-->
	    <div class="col-md-3 padding-top-10">
		<button type=submit class="btn btn-primary btn-large">
			Add Vendor
		</button>
	    </div>
	</div>
	</form>
       </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#vendor-new").addClass('active');
		$("#vendors-link").addClass('active');

		$(function() {
			$(".datepicker").datepicker({
		            changeMonth: true,
		            changeYear: true,
		            dateFormat: "yy-mm-dd",
			    yearRange: '1950:c',
			});
		});
	})
</script>
{% endblock %}

templates/agent/vendor_details.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block subnav %}
{% include "vendors_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">Vendor Details</p>
	    </div>
	    <div class="section-data">
		<div class="row">
		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-4">
			    <p class="section-data-title">Personal Information</p>
		    </div>
		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-8">
		    </div>
		</div>

		<div class="row">
		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-1">
		    </div>
		    
		    <div class="col-xsm-12 col-sm-12 col-md-6 col-lg-2">
			    <img width=150 height=150 src="{{object.profile.url}}" alt="">
		    </div>

		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-3">
			    <p><b>First Name:</b> {{object.first_name}}</p>
			    <p><b>Phone:</b> {{object.phone}}</p>
			    <p><b>Guarantor:</b> {{object.guarantor}}</p>
		    </div>
		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-4">
			    <p><b>Last Name:</b> {{object.last_name}}</p>
			    <p><b>Hometown:</b> {{object.hometown}}</p>
			    <p><b>Guarantor Phone:</b> {{object.guarantor_phone}}</p>
		    </div>
		    <div class="col-xsm-12 col-sm-12 col-md-6 col-lg-1">
			    <a class="btn btn-primary" href="/vendors/update/{{object.pk}}">Edit</a>
		    </div>
		    <div class="col-xsm-12 col-sm-6 col-md-6 col-lg-1">
		    </div>
		</div>
		<hr class=section-separator>    
	        <p class="section-data-title">Unclosed Bookings</p>
		<div>
		    {% for sale in sales %}
			{% if sale.closed == False %}
			<div style="margin-bottom: 20px;">
			{{sale.date.isoformat}} 
			<span style="margin-left: 50px;">
				<a class="btn btn-danger" style="display: inline;" href="/sales/bookings/close/{{sale.pk}}">Close</a>
		        </span>
			</div>
			{% endif %}
			{% endfor %}
		</div>
            </div>
    </div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("#vendors-link").addClass("active");
		$("#vendor-all").addClass("active");
	})

      google.charts.load("current", {packages:["calendar", "corechart"]});
      google.charts.setOnLoadCallback(drawChart);

   function drawChart() {
       var dataTable = new google.visualization.DataTable();
       dataTable.addColumn({ type: 'date', id: 'Date' });
       dataTable.addColumn({ type: 'number', id: 'present/absent' });
       dataTable.addRows
      ([{% for sale in sales %}
       [ new Date("{{sale.date.isoformat}}"), {{sale.total}} ],
       {% endfor %}
        ]);

       var calendar_chart = new google.visualization.Calendar(document.getElementById('calendar_basic'));
       var line_chart = new google.visualization.LineChart(document.getElementById('line_chart'));

       var calendar_options = {
         title: "Daily Sales Profiling",
	 titleTextStyle: {
		 fontSize: 2,
	 },
	 width: 1200,
         height: 170,
       };

       var line_options = {
         title: "Daily Sales Trend",
	 titleTextStyle: {
		 fontSize: 24,
		 color: "#999"
	 },
	 width: 1000,
         height: 250,
	 hAxis: {
	     gridlines: {count: 20} 
	 },
       };

       calendar_chart.draw(dataTable, calendar_options);
       line_chart.draw(dataTable, line_options);
   }
</script>

{% endblock %}