agent/urls.py
from django.conf.urls import url
from django.views.generic import UpdateView
from views import *
from models import Vendor
from forms import VendorForm

urlpatterns = [
    url(r'^all/$', VendorListView.as_view(), name="all"),
    url(r'^all/json$', VendorJSONListView.as_view(), name="all-json"),
    url(r'^new/$', VendorCreate.as_view(), name="new"),
    url(r'^details/(?P<pk>\d+)/$', VendorDetailView.as_view(), name="detail"),
    url(r'^update/(?P<pk>\d+)/$', UpdateView.as_view(
        model=Vendor,
        form_class=VendorForm,
        template_name='agent/vendor_create_form.html',
        success_url='/vendors/all/'
        ), name="update"),
]

fanaider/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^vendors/', include('agent.urls', namespace='vendors')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

sales/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^bookings/all/$', AllBookingView.as_view(), name="bookings-all"),
    url(r'^bookings/add/$', NewBookingView.as_view(), name="add-booking"),
    url(r'^metrics/$', NewBookingView.as_view(), name="metrics"),
    url(r'^bookings/edit/(?P<pk>\d+)/$', BookingUpdateView.as_view(), name="edit"),
    url(r'^bookings/close/(?P<pk>\d+)/$', CloseBookingView.as_view(), name="close"),
    url(r'^bookings/pay/(?P<pk>\d+)/$', PayBookingView.as_view(), name="pay"),
    url(r'^bookings/view/(?P<pk>\d+)/$', BookingsDetailView.as_view(), name="view"),
]

sales/models.py
from __future__ import unicode_literals

from django.db import models

from agent.models import Vendor
from utils.models import Product

class VendorBooking(models.Model):
    date   = models.DateField()
    vendor = models.ForeignKey(Vendor)
    closed = models.BooleanField(default=False)
    paid   = models.BooleanField(default=False)
    total  = models.FloatField(blank=True, null=True, default=0.0)
    amount_paid = models.FloatField(blank=True, null=True, default=0.0)

    class Meta:
        ordering= ['-date']

    def __unicode__(self):
        return self.vendor.first_name + " " + self.vendor.last_name

    '''
    def get_total(self):
        total = 0
        bookings = self.productbooking_set.all()
        for booking in bookings:
            total = total + booking.booking*booking.product.unit_price 
        return total

    def save(self, *args, **kwargs):
        self.total = self.get_total()
        return super(VendorBooking, self).save(*args, **kwargs)
    '''

class ProductBooking(models.Model):
    product = models.ForeignKey(Product)
    master_booking = models.ForeignKey(VendorBooking)
    booking = models.IntegerField()
    returns = models.IntegerField(default=0)
    

purchases/forms.py
from django import forms
from models import PAYMENT_TYPE, PURCHASE_TYPE

class ProductPurchaseForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_code = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_name = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=100)
    unit_price = forms.FloatField(required=False, widget=forms.HiddenInput())
    quantity = forms.IntegerField()

class DayPurchaseForm(forms.Form):
    invoice_number = forms.CharField(max_length=20);
    purchase_date = forms.DateField(input_formats=('%d-%m-%Y',))
    purchase_type = forms.ChoiceField(choices=PURCHASE_TYPE)
    payment_option = forms.ChoiceField(choices=PAYMENT_TYPE)

    issuing_bank = forms.CharField(required=False, max_length=50)
    account_number = forms.CharField(required=False, max_length=20)
    cheque_number = forms.CharField(required=False, max_length=10)
    cheque_date = forms.DateField(required=False, input_formats=('%d-%m-%Y',))
    amount_on_cheque = forms.FloatField(required=False)

    total_cash = forms.FloatField(required=False)
    
class PaymentForm(forms.Form):
    payment_option = forms.ChoiceField(choices=PAYMENT_TYPE)

    issuing_bank = forms.CharField(required=False, max_length=50)
    account_number = forms.CharField(required=False, max_length=20)
    cheque_number = forms.CharField(required=False, max_length=10)
    cheque_date = forms.DateField(required=False, input_formats=('%d-%m-%Y',))
    amount_on_cheque = forms.FloatField(required=False)

    total_cash = forms.FloatField(required=False)

class DamageCountForm(forms.Form):
    date = forms.DateField(input_formats=('%d-%m-%Y',))
    
class ProductDamageForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_code = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_name = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=100)
    unit_price = forms.FloatField(required=False, widget=forms.HiddenInput())
    quantity = forms.IntegerField()

sales/forms.py
from django import forms
from agent.models import Vendor
from agent.models import ShopAssistant


class BookingFormGet(forms.Form):
    date = forms.DateField(input_formats=('%d-%m-%Y',))
    vendor = forms.ModelChoiceField(Vendor.objects.all())

    def __init__(self, shop_id=None, **kwargs):
        super(BookingFormGet, self).__init__(**kwargs)
        if shop_id:
            self.fields['vendor'] = forms.ModelChoiceField(
                Vendor.objects.filter(shop__id=shop_id))
        else:
            self.fields['vendor'] = forms\
                .ModelChoiceField(Vendor.objects.all())


class BookingFormPost(forms.Form):
    vendor = forms.ModelChoiceField(Vendor.objects.all())
    date = forms.DateField(input_formats=('%d-%m-%Y',))


class UpdateBookingForm(forms.Form):
    vendor = forms.ModelChoiceField(Vendor.objects.all(), disabled=True)
    date = forms.DateField(input_formats=('%d-%m-%Y',), disabled=True)


class ProductBookingForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput())
    product_name = forms.CharField(required=False, widget=forms.HiddenInput())
    product_code = forms.CharField(required=False, widget=forms.HiddenInput())
    booking = forms.IntegerField(min_value=0)


class SalesClosureForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput())
    product_name = forms.CharField(required=False, widget=forms.HiddenInput())
    product_code = forms.CharField(required=False, widget=forms.HiddenInput())
    unit_price = forms.CharField(required=False, widget=forms.HiddenInput())
    booking = forms.IntegerField(min_value=0, required=False, disabled=True)
    returns = forms.IntegerField(min_value=0)


class BookingsDetailForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput())
    product_name = forms.CharField(required=False, widget=forms.HiddenInput())
    product_code = forms.CharField(required=False, widget=forms.HiddenInput())
    unit_price = forms.CharField(required=False, widget=forms.HiddenInput())
    booking = forms.IntegerField(min_value=0, required=False, disabled=True)
    returns = forms.IntegerField(min_value=0, required=False, disabled=True)


class BookingPaymentForm(forms.Form):
    vendor = forms.ModelChoiceField(Vendor.objects.all(),
                                    required=False, disabled=True)
    date = forms.DateField(input_formats=('%d-%m-%Y',),
                           required=False, disabled=True)
    sale_total = forms.FloatField(required=False, disabled=True)
    payment_total = forms.FloatField(min_value=0.0)

sales/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, TemplateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.views import View
from django.forms import formset_factory
from django.db.models import Sum, Count
from django.db.models.functions import TruncDate
from django.forms.models import model_to_dict

from forms import *
from models import *
from agent.models import ShopAssistant

from utils.models import vending_products, Product
from purchases.models import *
import itertools
import urllib

def build_url_with_parameters(*args, **kwargs):
    get = kwargs.pop('get', {})
    url = reverse(*args, **kwargs)
    if get:
        print get
        url +='?'+urllib.urlencode(get)
    return url

class NewBookingView(LoginRequiredMixin, TemplateView):
    template_name = 'sales/new_booking.html'
    login_url = '/login/'

    def get_initial_data(self):
        products = Product.objects.all()
        initial_data = []

        for code in vending_products:
            for p in products:
                if p.code == code:
                    initial_data.append(
                        {'product_id': p.id,
                         'product_code': p.code,
                         'booking': 0,
                         'product_name': p.name})
        return initial_data


    def get(self, request, *args, **kwargs):
        ProductBookingFormSet = formset_factory(ProductBookingForm, extra=0)
        booking_form = BookingFormGet(request.user.shopassistant.shop.id)

        formset = ProductBookingFormSet(initial=self.get_initial_data())
        return self.render_to_response(self.get_context_data(formset=formset,
                                                             booking_form=booking_form))

    def post(self, request, *args, **kwargs):
        booking_form = BookingFormPost(request.POST)

        ProductBookingFormSet = formset_factory(ProductBookingForm, extra=0)
        formset = ProductBookingFormSet(request.POST)

        if booking_form.is_valid() and formset.is_valid():
            booking_form_clean = booking_form.cleaned_data
            vendor_booking = VendorBooking()
            existing_bookings = VendorBooking.objects.filter(date=booking_form_clean.get('date'))
            vendors = [booking.vendor for booking in existing_bookings.all()]

            if booking_form_clean.get('vendor') in vendors:
                booking_form.add_error('vendor', "This Vendor has already been booked for the day")
                return self.render_to_response(self.get_context_data(formset=formset, booking_form=booking_form))
            vendor_booking.date = booking_form_clean.get('date')
            vendor_booking.vendor = booking_form_clean.get('vendor')

            prod_count = 0
            for form in formset:
                cleaned_data = form.cleaned_data
                if cleaned_data.get('booking')==0 or cleaned_data.get('booking')=="":
                    continue
                else:
                    prod_count = prod_count + 1
            if prod_count == 0:
                form.add_error('booking', "At least one product must have a booking greater than 0")
                return self.render_to_response(self.get_context_data(formset=formset, booking_form=booking_form))
            else:
                vendor_booking.save()
                for form in formset:
                    product_booking = ProductBooking()
                    product_booking.booking = form.cleaned_data.get('booking')
                    product_booking.product = Product.objects.get(pk=form.cleaned_data.get('product_id'))
                    product_booking.master_booking = vendor_booking
                    product_booking.save()
            return HttpResponseRedirect(reverse('sales:bookings-all'))

        else:
            return self.render_to_response(self.get_context_data(formset=formset, booking_form=booking_form))

def all_booking_json(request):
    for book in ProductBooking.objects.all():
        print book
    return HttpResponse(status=200)

class AllBookingView(LoginRequiredMixin, ListView):
    template_name = 'sales/all_booking.html'
    model = VendorBooking
    login_url = '/login/'
    booking_dates = []


    def get_queryset(self, **kwargs):
        shop = ShopAssistant.objects.get(user=self.request.user).shop
        index = self.request.GET.get('page')
        if index==None:
            index = 1
        booking_dates = VendorBooking.objects\
            .filter(vendor__shop=shop)\
            .annotate(_date=TruncDate('date'))\
                                   .values('date')\
                                   .annotate(Sum('amount_paid'))
        if not booking_dates:
            return {}

        self.request.session['page'] = index

        self.booking_dates = booking_dates
        booking_date = booking_dates[int(index)-1].get('date')
        total = booking_dates[int(index)-1].get('amount_paid__sum')
        objects = VendorBooking.objects\
            .filter(date=booking_date, vendor__shop=shop)\
            .prefetch_related('productbooking_set', \
                              'productbooking_set__product')\
            .select_related('vendor')
        sales_dict = {}
        sales_container = []

        sales_dict['date'] = booking_date
        sales_dict['sales'] = objects
        sales_dict['total'] = total
        sales_container.append(sales_dict)
        return sales_container

    def get_page_object(self):
        index = self.request.GET.get('page')
        if index==None:
            index=1
        index = int(index)
        total_pages = len(self.booking_dates)
        page_dict = {}
        page_dict['has_previous'] = index > 1
        page_dict['has_next'] = index < total_pages

        page_dict['next_page_number'] = index + 1
        page_dict['previous_page_number'] = index - 1

        page_dict['number'] = index

        return page_dict


    def get_context_data(self, **kwargs):
        q_set = self.get_queryset()
        if not q_set:
            return {}
        context = super(AllBookingView, self).get_context_data(**kwargs)
        daily_sales_dict = {}

        for sale in q_set[0].get('sales'):
            product_sale_list = []
            for code in vending_products:
                found =0
                print "beginning for"
                for product_booking in sale.productbooking_set.all():
                    print "beginning loop"
                    if product_booking.product.code == code:
                        print product_booking
                        product_sale_list.append(product_booking.booking)
                        if sale.closed == True:
                            product_sale_list.append(product_booking.returns)
                            product_sale_list\
                                .append(product_booking.booking\
                                        -product_booking.returns)
                        else:
                            product_sale_list.append(" ")
                            product_sale_list.append(" ")
                        found =1
                        break
                if found==0:
                    product_sale_list.append(" ")
                    product_sale_list.append(" ")
                    product_sale_list.append(" ")

            daily_sales_dict[sale.pk] = product_sale_list

        context['daily_sales_dict']   = daily_sales_dict
        context['day_total'] = q_set[0].get('total')

        total_pages = len(self.booking_dates)

        if total_pages < 2:
            context['is_paginated'] = False
        else:
            context['is_paginated'] = True
            context['page_obj'] = self.get_page_object()

            index = self.request.GET.get('page')
            if index==None:
                index=1
            index = int(index)

            left_margin = index - 3
            if left_margin <= 0:
                right_margin = 7
                if right_margin > total_pages:
                    right_margin = total_pages
                context['page_range'] = range(1, right_margin+1)

            else:
                right_margin = index + 3
                if right_margin > total_pages:
                    left_margin = left_margin-(right_margin-total_pages)
                    right_margin = total_pages
                if left_margin <= 0:
                    left_margin=1
                context['page_range'] = range(left_margin, index) + range(index, right_margin+1)
        return context

class BookingUpdateView(LoginRequiredMixin, FormView):
    template_name = 'sales/new_booking.html'
    form_class = UpdateBookingForm
    login_url ='/login/'
    vendor_booking = None

    def get_context_data(self, **kwargs):
        context = super(BookingUpdateView, self).get_context_data(**kwargs)
        data = {'vendor': self.vendor_booking.vendor.id, 'date': self.vendor_booking.date}

        ProductBookingFormSet = formset_factory(ProductBookingForm, extra=0)

        formset = ProductBookingFormSet(initial=self.get_initial_data())

        booking_form = UpdateBookingForm(initial=data)

        context['formset'] = formset
        context['booking_form'] = booking_form
        return context

    def get_initial_data(self):
        initial_data = []
        for code in vending_products:
            for p in self.vendor_booking.productbooking_set.all():
                if p.product.code == code:
                    initial_data.append(
                    {'product_id': p.product.id,
                     'product_code': p.product.code,
                     'booking': p.booking,
                     'product_name': p.product.name})
        return initial_data

templates/sales/booking_pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&lt next day</a></li>
    {% else %}
      <li class="disabled"><span>&lt next day</span></li>
    {% endif %}
    {% for i in page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">prev day &gt</a></li>
    {% else %}
      <li class="disabled"><span>prev day &gt</span></li>
    {% endif %}
  </ul>

{% endif %}

templates/sales/edit_booking.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block subnav %}
{% include "sales_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">Edit Booking</p>
	    </div>
	    <div class="section-data">
		   {% if booking_form.errors or form.errors %}
		   <div class="alert-danger">The data you provided has errors. Please correct them.</div>
		   {% endif %}
        <form action="#" method="post" role="form">
		{{ formset.management_form }}
		{%csrf_token%}
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_vendor">Vendor:</label>
			      {% render_field booking_form.vendor class+="form-control" %}
			      {% if booking_form.vendor.errors %}
			          {% for error in booking_form.vendor.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_vendor").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="form-group col-md-3">
			      <label class="control-label" for="id_purchase_date">Date:</label>
			      {% render_field booking_form.date class+="form-control datepicker" %}
			      {% if booking_form.date.errors %}
			          {% for error in booking_form.date.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_date").addClass("has-error")</script>
			      {% endif %}
			</div>
		</div>
		<hr>
	<table class="table table-striped table-bordered purchases">
		<thead>
			<tr>
				<th>Product Code</th>
				<th>Product Name</th>
				<th>Product Bookings</th>
			</tr>
		</thead>
		<tbody>
			{% for form in formset %}
			{{form.product_id}}
			{{form.product_code}}
			{{form.product_name}}
			<tr class="product_row" id="product_{{form.product_id.value}}">	
				<td>{{form.product_code.value}}</td>
				<td>{{form.product_name.value}}</td>
				<td class="booking_cell">{% render_field form.booking class+="form-control booking-box"%}</td>
			      {% if form.booking.errors %}
			          {% for error in form.booking.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$(".booking-box").addClass("has-error")</script>
			      {% endif %}
			</tr>	
			{% endfor %}
		</tbody>
	</table>
	<hr class="purchase_form_divider">
	<div class=row>
	    <div class="col-md-4"></div> <!-- spacer-->
	    <div class="col-md-4"></div> <!-- spacer-->
	    <div class="col-md-4 padding-top-10">
		<button type=submit class="btn btn-primary btn-large">
			Save Booking
		</button>
	    </div>
	</div>
	</form>
       </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}

<script type="text/javascript">
	$(document).ready(function(){
		$("#sales-link").addClass("active");
		$("#sales-bookings").addClass("active");
		$(".datepicker").datepicker({
		    changeMonth: true,
		    changeYear: true,
		    dateFormat: "dd-mm-yy",
		    maxDate: '0'
		});
	})
</script>
{% endblock %}

templates/sales/new_booking.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block subnav %}
{% include "sales_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">New Booking</p>
	    </div>
	    <div class="section-data">
		   {% if booking_form.errors or form.errors %}
		   <div class="alert-danger">The data you provided has errors. Please correct them.</div>
		   {% endif %}
        <form action="#" method="post" role="form">
		{{ formset.management_form }}
		{%csrf_token%}
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_vendor">Vendor:</label>
			      {% render_field booking_form.vendor class+="form-control" %}
			      {% if booking_form.vendor.errors %}
			          {% for error in booking_form.vendor.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_vendor").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="form-group col-md-3">
			      <label class="control-label" for="id_purchase_date">Date:</label>
			      {% render_field booking_form.date class+="form-control datepicker" %}
			      {% if booking_form.date.errors %}
			          {% for error in booking_form.date.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_date").addClass("has-error")</script>
			      {% endif %}
			</div>
		</div>
		<hr>
	<table class="table table-striped table-bordered purchases">
		<thead>
			<tr>
				<th>Product Code</th>
				<th>Product Name</th>
				<th>Product Bookings</th>
			</tr>
		</thead>
		<tbody>
			{% for form in formset %}
			{{form.product_id}}
			{{form.product_code}}
			{{form.product_name}}
			<tr class="product_row" id="product_{{form.product_id.value}}">	
				<td>{{form.product_code.value}}</td>
				<td>{{form.product_name.value}}</td>
				<td class="booking_cell">{% render_field form.booking class+="form-control booking-box"%}</td>
			      {% if form.booking.errors %}
			          {% for error in form.booking.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$(".booking-box").addClass("has-error")</script>
			      {% endif %}
			</tr>	
			{% endfor %}
		</tbody>
	</table>
	<hr class="purchase_form_divider">
	<div class=row>
	    <div class="col-md-4"></div> <!-- spacer-->
	    <div class="col-md-4"></div> <!-- spacer-->
	    <div class="col-md-4 padding-top-10">
		<button type=submit class="btn btn-primary btn-large">
			Save Booking
		</button>
	    </div>
	</div>
	</form>
       </div>
    </div>
</div>

{% endblock %}
{% block footer %}
{% include "footer.html" %}

<script type="text/javascript">
	$(document).ready(function(){
		$("#sales-link").addClass("active");
		$("#add-bookings").addClass("active");
		$(".datepicker").datepicker({
		    changeMonth: true,
		    changeYear: true,
		    dateFormat: "dd-mm-yy",
		    maxDate: '0'
		});
	})
</script>
{% endblock %}

templates/sales/pay_booking.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block subnav %}
{% include "sales_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">Pay Booking</p>
	    </div>
	    <div class="section-data">
		   {% if form.errors %}
		   <div class="alert-danger">The data you provided has errors. Please correct them.</div>
		   {% endif %}
        <form action="#" method="post" role="form">
		{%csrf_token%}
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_vendor">Vendor:</label>
			      {% render_field form.vendor class+="form-control" %}
			</div>
			<div class="form-group col-md-4"></div> 
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_date">Date:</label>
			      {% render_field form.date class+="form-control" %}
			</div>
		</div>
		<div class="row">
			<div class="form-group col-md-8"></div> 
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_sale_total">Sales GHC:</label>
			      {% render_field form.sale_total class+="form-control right-align" %}
			</div>
		</div>
		<hr class=padding-bottom-10>
		<div class="row">
			<div class="form-group col-md-8"></div> 
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_payment_total">Amount Paid GHC:</label>
			      {% render_field form.payment_total class+="form-control right-align" %}
			      {% if form.payment_total.errors %}
				  {% for error in form.payment_total.errors %}
				      <div class="alert-danger">{{error}}</div>
				  <script>$("#id_payment_total").addClass("has-error")</script>
				  {% endfor%}
			      {% endif %}
			</div>
		</div>
	<div class=row>
	    <div class="col-md-8"></div> <!-- spacer-->
	    <div class="col-md-4 padding-top-10">
		<button type=submit class="btn btn-primary btn-large">
			Authorize Payment
		</button>
	    </div>
	</div>
	</form>
       </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% include "footer.html" %}

<script type="text/javascript">
	$(document).ready(function(){
		$("#sales-bookings").addClass('active');
		$("#sales-link").addClass('active');

		$(function() {
			$(".datepicker").datepicker({
		            changeMonth: true,
		            changeYear: true,
		            dateFormat: "yy-mm-dd",
			    yearRange: '1950:c',
			});
		});
	})
</script>
{% endblock %}