agent/urls.py
from django.conf.urls import url
from django.views.generic import UpdateView
from views import *
from models import Vendor
from forms import VendorForm

urlpatterns = [
    url(r'^all/$', VendorListView.as_view(), name="all"),
    url(r'^all/json$', VendorJSONListView.as_view(), name="all-json"),
    url(r'^new/$', VendorCreate.as_view(), name="new"),
    url(r'^details/(?P<pk>\d+)/$', VendorDetailView.as_view(), name="detail"),
    url(r'^update/(?P<pk>\d+)/$', UpdateView.as_view(
        model=Vendor,
        form_class=VendorForm,
        template_name='agent/vendor_create_form.html',
        success_url='/vendors/all/'
        ), name="update"),
]

fanaider/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^vendors/', include('agent.urls', namespace='vendors')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

purchases/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^all/$', DayPurchaseListView.as_view(), name="all"),
    url(r'^damages/all/$', DamageCountListView.as_view(), name="damages-all"),
    url(r'^new/$', NewPurchaseView.as_view(), name="new"),
    url(r'^damages/new/$', NewDamageCountView.as_view(), name="damages-new"),
    url(r'^metrics/$', PurchaseMetricsView.as_view(), name="metrics"),
    url(r'^detail/(?P<pk>\d+)/$', DayPurchaseDetail.as_view(), name="detail"),
]

purchases/models.py
from __future__ import unicode_literals

from django.db import models
from utils.models import Product
from agent.models import Shop

PURCHASE_TYPE = [
    (0, "Credit Purchase"),
    (1, "Cash Purchase")
]

PAYMENT_TYPE = [
    (0, "Cheque Payment"),
    (1, "Cash Payment")
]

class Cheque(models.Model):
    bank = models.CharField(max_length=100)
    account_number = models.CharField(max_length=100)
    cheque_date = models.DateField()
    cheque_number = models.IntegerField()

class ProductPayment(models.Model):
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    payment_type = models.IntegerField(choices=PAYMENT_TYPE, default=1)
    amount_paid = models.FloatField()
    cheque = models.ForeignKey(Cheque, null=True, blank=True)

class DayPurchase(models.Model):
    shop = models.ForeignKey(Shop)
    date = models.DateField()
    purchase_type = models.IntegerField(choices=PURCHASE_TYPE, default=1)
    invoice_number = models.CharField(max_length=100)
    payment = models.ForeignKey(ProductPayment, null=True, blank=True)
    total = models.FloatField()
    month = models.IntegerField()

    class Meta:
        ordering = ['-date']

    def get_total(self):
        total = 0
        purchases = self.productpurchase_set.select_related('product').all()
        for purchase in purchases:
            total = total + purchase.quantity*purchase.product.unit_price
        return total

    def get_payment_status(self):
        if self.payment == None:
            return "Unpaid"
        else:
            return "Paid"

    def save(self, *args, **kwargs):
        self.total = self.get_total()
        self.month = self.date.month
        return super(DayPurchase, self).save(*args, **kwargs)

class ProductPurchase(models.Model):
    product = models.ForeignKey(Product)
    quantity = models.IntegerField()
    master_purchase = models.ForeignKey(DayPurchase)

class DamageCount(models.Model):
    shop = models.ForeignKey(Shop)
    date = models.DateField()
    total = models.FloatField()
    month = models.IntegerField()

    def __unicode__(self):
        return str(self.total)

    def get_total(self):
        total = 0
        damages = self.productdamage_set.select_related('product').all()
        for damage in damages:
            total = total + damage.quantity*damage.product.unit_price
        return total

    def save(self, *args, **kwargs):
        self.total = self.get_total()
        self.month = self.date.month
        return super(DamageCount, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-month']

class ProductDamage(models.Model):
    product = models.ForeignKey(Product)
    quantity = models.IntegerField()
    master_damage = models.ForeignKey(DamageCount)

purchases/forms.py
from django import forms
from models import PAYMENT_TYPE, PURCHASE_TYPE

class ProductPurchaseForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_code = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_name = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=100)
    unit_price = forms.FloatField(required=False, widget=forms.HiddenInput())
    quantity = forms.IntegerField()

class DayPurchaseForm(forms.Form):
    invoice_number = forms.CharField(max_length=20);
    purchase_date = forms.DateField(input_formats=('%d-%m-%Y',))
    purchase_type = forms.ChoiceField(choices=PURCHASE_TYPE)
    payment_option = forms.ChoiceField(choices=PAYMENT_TYPE)

    issuing_bank = forms.CharField(required=False, max_length=50)
    account_number = forms.CharField(required=False, max_length=20)
    cheque_number = forms.CharField(required=False, max_length=10)
    cheque_date = forms.DateField(required=False, input_formats=('%d-%m-%Y',))
    amount_on_cheque = forms.FloatField(required=False)

    total_cash = forms.FloatField(required=False)
    
class PaymentForm(forms.Form):
    payment_option = forms.ChoiceField(choices=PAYMENT_TYPE)

    issuing_bank = forms.CharField(required=False, max_length=50)
    account_number = forms.CharField(required=False, max_length=20)
    cheque_number = forms.CharField(required=False, max_length=10)
    cheque_date = forms.DateField(required=False, input_formats=('%d-%m-%Y',))
    amount_on_cheque = forms.FloatField(required=False)

    total_cash = forms.FloatField(required=False)

class DamageCountForm(forms.Form):
    date = forms.DateField(input_formats=('%d-%m-%Y',))
    
class ProductDamageForm(forms.Form):
    product_id = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_code = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=20)
    product_name = forms.CharField(required=False, widget=forms.HiddenInput(), max_length=100)
    unit_price = forms.FloatField(required=False, widget=forms.HiddenInput())
    quantity = forms.IntegerField()

purchases/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum

from utils.models import Product
from purchases.forms import *
from django.forms import formset_factory
from purchases.models import *
from agent.models import ShopAssistant

from utils.models import vending_products
import calendar
import datetime

class NewPurchaseView(LoginRequiredMixin, FormView):
    template_name = 'purchases/new_purchase.html'
    form_class = ProductPurchaseForm
    login_url = '/login/'

    def get_initial_data(self):
        products = Product.objects.all()
        product_count = products.count()
        initial_data = [
            {'product_id': product.id,
             'product_code': product.code,
             'product_name': product.name,
             'unit_price': product.unit_price,
             'quantity': 0} for product in products]
        return initial_data

    def get(self, request, *args, **kwargs):
        ProductPurchaseFormSet = formset_factory(ProductPurchaseForm, extra=0)
        purchase_form = DayPurchaseForm()
        formset = ProductPurchaseFormSet(initial=self.get_initial_data())
        return self.render_to_response(self.get_context_data(formset=formset, purchase_form=purchase_form))

    def post(self, request, *args, **kwargs):
        ProductPurchaseFormSet = formset_factory(ProductPurchaseForm, extra=0)
        purchase_form = DayPurchaseForm(request.POST)
        formset = ProductPurchaseFormSet(request.POST)
        # only called when form is valid with invoice_number, date and purchase_type provided
        if purchase_form.is_valid():
            cleaned_data = purchase_form.cleaned_data
            purchase_type = cleaned_data.get('purchase_type')
            if purchase_type == '1':
                payment_option = cleaned_data.get('payment_option')
                if payment_option == '0':
                    if check_cheque(purchase_form) == True:
                        return self.form_invalid(formset, purchase_form)
        if formset.is_valid():
            print "problem with form"
            from agent.models import ShopAssistant
            shop = ''
            if 'shopassistants' in [group.name for group in request.user.groups.all()]:
                shop = ShopAssistant.objects.get(user=request.user).shop
            elif u'agents' in [group.name for group in request.user.groups.all()]:
                shop = user.agent.shop
            prod_count = 0
            for form in formset:
                cleaned_data = form.cleaned_data
                if cleaned_data.get('quantity')==0 or cleaned_data.get('quantity') == "":
                    continue
                else:
                    prod_count = prod_count + 1
            if prod_count == 0:
                form.add_error('quantity', "At least one Product must have a quantity greater than 0")
                return self.form_invalid(formset, purchase_form)
            # Everything is alright.... Begin saving.
            else:
                day_purchase = DayPurchase()
                day_purchase.shop = shop
                day_purchase.invoice_number = purchase_form.cleaned_data.get('invoice_number')
                purchase_type = purchase_form.cleaned_data.get('purchase_type')
                day_purchase.date = purchase_form.cleaned_data.get('purchase_date')
                day_purchase.purchase_type = purchase_type
                #CREDIT
                if purchase_type == '0':
                    day_purchase.save()
                #CASH
                else:
                    payment_option = purchase_form.cleaned_data.get('payment_option')
                    payment = ProductPayment()
                    payment.payment_type = payment_option

                    #CASH
                    if payment_option == '1':
                        payment.amount_paid  =  purchase_form.cleaned_data.get('total_cash')

                    #CHEQUE
                    else:
                        cheque = Cheque()
                        cheque.bank = purchase_form.cleaned_data.get('issuing_bank')
                        cheque.account_number = purchase_form.cleaned_data.get('account_number')
                        cheque.cheque_number = purchase_form.cleaned_data.get('cheque_number')
                        cheque.cheque_date = purchase_form.cleaned_data.get('cheque_date')
                        cheque.save()
                        payment.cheque = cheque
                        payment.amount_paid = purchase_form.cleaned_data.get('amount_on_cheque')
                    payment.save()
                    day_purchase.payment = payment
                    day_purchase.save()

                for form in formset:
                    # No quantity
                    cleaned_data = form.cleaned_data
                    if cleaned_data.get('quantity')==0 or cleaned_data.get('quantity')=="":
                        continue
                    else:
                        pid = cleaned_data.get('product_id')
                        quantity = cleaned_data.get('quantity')
                        product = Product.objects.get(pk=pid)
                        product_purchase = ProductPurchase()
                        product_purchase.product = product
                        product_purchase.quantity = quantity
                        product_purchase.master_purchase = day_purchase
                        product_purchase.save()
                day_purchase.save()

                return self.form_valid()
        else:
            for form in formset:
                try:
                    form.errors.pop('quantity')
                except KeyError:
                    continue
            form.add_error('quantity', "Quantity field cannot be empty.")
            return self.form_invalid(formset, purchase_form)

    def form_invalid(self, formset, purchase_form):
        return self.render_to_response(self.get_context_data(formset=formset, purchase_form=purchase_form))

    def form_valid(self):
        return HttpResponseRedirect(reverse('purchases:all'))

class NewDamageCountView(LoginRequiredMixin, FormView):
    template_name = 'purchases/new_damages.html'
    form_class = DamageCountForm
    login_url = '/login/'

    def get_initial_data(self):
        products = Product.objects.all()
        product_count = products.count()
        initial_data = [
            {'product_id': product.id,
             'product_code': product.code,
             'product_name': product.name,
             'unit_price': product.unit_price,
             'quantity': 0} for product in products]
        return initial_data

    def get(self, request, *args, **kwargs):
        ProductDamageFormSet = formset_factory(ProductDamageForm, extra=0)
        damage_form = DamageCountForm()
        formset = ProductDamageFormSet(initial=self.get_initial_data())
        return self.render_to_response(self.get_context_data(formset=formset, damage_form=damage_form))

    def post(self, request, *args, **kwargs):
        ProductDamageFormSet = formset_factory(ProductDamageForm, extra=0)
        damage_form = DamageCountForm(request.POST)
        formset = ProductDamageFormSet(request.POST)
        # only called when form is valid with invoice_number, date and purchase_type provided
        if damage_form.is_valid():
            cleaned_data = damage_form.cleaned_data
        if formset.is_valid():
            print "problem with form"
            from agent.models import ShopAssistant
            shop = ''
            if 'shopassistants' in [group.name for group in request.user.groups.all()]:
                shop = ShopAssistant.objects.get(user=request.user).shop
            elif u'agents' in [group.name for group in request.user.groups.all()]:
                shop = user.agent.shop
            prod_count = 0
            for form in formset:
                cleaned_data = form.cleaned_data
                if cleaned_data.get('quantity')==0 or cleaned_data.get('quantity') == "":
                    continue
                else:
                    prod_count = prod_count + 1
            if prod_count == 0:
                form.add_error('quantity', "At least one Product must have a quantity greater than 0")
                return self.form_invalid(formset, damage_form)
            # Everything is alright.... Begin saving.
            else:
                damage_count = DamageCount()
                damage_count.shop = shop
                damage_count.date = damage_form.cleaned_data.get('date')
                damage_count.save()

                for form in formset:
                    # No quantity
                    cleaned_data = form.cleaned_data
                    if cleaned_data.get('quantity')==0 or cleaned_data.get('quantity')=="":
                        continue
                    else:
                        pid = cleaned_data.get('product_id')
                        quantity = cleaned_data.get('quantity')
                        product = Product.objects.get(pk=pid)
                        product_damage = ProductDamage()
                        product_damage.product = product
                        product_damage.quantity = quantity
                        product_damage.master_damage = damage_count
                        product_damage.save()
                damage_count.save()

                return self.form_valid()
        else:
            for form in formset:
                try:
                    form.errors.pop('quantity')
                except KeyError:
                    continue

templates/purchases/all_purchases.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% load dict_filter %}
{% block subnav %}
{% include "purchases_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">All Purchases</p>
	    </div>
	    <div class="section-data purchases-list">
                 {% regroup object_list by date|date:"F" as purchases %}
                   {% for purchase_list in purchases %}
		   <div class=month-header>
		   <h3 class=month-name>{{purchase_list.grouper}} <span class="badge purchase-count">{{purchase_list.list|length}}</span></h3>
		   {% with month=purchase_list.grouper %}
		   <h3 class=month-total>GHS {{month_sum_dict|get_item:month|floatformat:2|intcomma}}</h3>
		   {% endwith %}
                   </div>
                    {% for purchase in purchase_list.list %}
		    <a href="../detail/{{purchase.pk}}" class=purchase-item-link>
		    <div class="row purchase-item">
			    <div class="col-md-2">
			       {{purchase.date}} 
			    </div>
			    <div class="col-md-3">
			       {{purchase.get_purchase_type_display}} 
			    </div>
			    <div class="col-md-3">
			       {{purchase.invoice_number}} 
			    </div>
			    <div class="col-md-2 right-align">
			       {{purchase.total|floatformat:2|intcomma}} 
			    </div>
			    <div class="col-md-2">
				    <div class="right-align">
				    <span class="badge {{purchase.get_payment_status}}">{{purchase.get_payment_status}}</span></div>
			    </div>
		    </div></a>
		    {% endfor %}
		    {% empty %}
		    <h3> You have not made any purchases yet</h3>
		    {% endfor %}
            </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#purchases-link").addClass("active");
		$("#purchase-all").addClass("active");
		$(function() {
			$(".datepicker").datepicker({
		            changeMonth: true,
		            changeYear: true,
		            dateFormat: "dd-mm-yy"	    
			})
		});
	})
</script>
{% endblock %}

templates/purchases/all_vendors.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% block subnav %}
{% include "vendors_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">All Vendors</p>
	    </div>
	    <div class="section-data">
            </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#purchases-link").addClass("active");
		$("#purchase-all").addClass("active");
		$(function() {
			$(".datepicker").datepicker({
		            changeMonth: true,
		            changeYear: true,
		            dateFormat: "dd-mm-yy"	    
			})
		});
	})
</script>
{% endblock %}

templates/purchases/purchase_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load mathfilters %}
{% load humanize %}
{% block subnav %}
{% include "purchases_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">Purchase Detail</p>
	    </div>
	    <div class="section-data">
		    {% if form.errors %}
		        <div class="alert-danger">The data you provided has some issues. Please revise it and try again.</div>
		    {% endif %}
		<div class="row">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_invoice_number">Invoice Number:</label>
			      <input class="form-control" type="text" id="id_invoice_number" disabled value={{object.invoice_number}}>
			</div>
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="form-group col-md-3">
			      <label class="control-label" for="id_purchase_date">Date:</label>
			      <input class="form-control" type="text" id="id_purchase_date" disabled value="{{object.date|date:"l, d F Y"}}">
			</div>
		</div>
		<div class="row">
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="col-md-4"></div> <!-- spacer-->
			<div class="form-group col-md-3">
			      <label class="control-label" for="id_purchase_type">Purchase Type:</label>
			      <input class="form-control" type="text" id="id_purchase_type" disabled value={{object.get_purchase_type_display}}>
			</div>
		</div>
	<table class="table table-striped table-bordered purchases">
		<thead>
			<tr>
				<th>Product Code</th>
				<th>Product Description</th>
				<th>Total Quantity Supplied</th>
				<th>Unit Price (GHS)</th>
				<th>Total Price (GHS)</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th class=hidden-cell></th>
				<th class=hidden-cell></th>
				<th class=hidden-cell></th>
				<th>Grand Total:</th>
				<th class=right-align id=gtotal>0.00</th>
			</tr>
		
		</tfoot>
		<tbody>
			{% for purchase in object.productpurchase_set.all %}
			<tr class="product_row">	
				<td>{{purchase.product.code}}</td>
				<td>{{purchase.product.name}}</td>
				<td class="quantity_cell right-align">{{purchase.quantity}}</td>
				<td class="unit_price right-align">{{purchase.product.unit_price}}</td>
				<td class="unit_total right-align">{{purchase.quantity|mul:purchase.product.unit_price|floatformat:2}}</td>
			</tr>	
			{% endfor %}
		
		</tbody>
	</table>
	<hr class="purchase_form_divider">
	<div id="payment_info_display">
		<div class="row">
		<div class="form-group col-md-4">
		      <label class="control-label" for="id_payment_option_display">Payment Option:</label>
		      <input class="form-control" type="text" id="id_payment_option_display" disabled value="{{object.payment.get_payment_type_display}}">
		</div>
		<div class="col-md-4"></div> <!-- spacer-->
		<div class="col-md-4"></div> <!-- spacer-->
		</div>
		<div class="row">
		<div id="cash_option_display">
			<div class="form-group col-md-4">
			      <label class="control-label" for="">Amount Paid:</label>
		      <input class="form-control right-align" type="text" id="" disabled value={{object.payment.amount_paid|floatformat:2|intcomma}}>
			</div>
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="col-md-4"></div> <!-- spacer-->
		</div>
		<div id="cheque_option_display">
			<div class="form-group col-md-4">
			      <label class="control-label" for="">Bank:</label>
		              <input class="form-control" type="text" id="" disabled value="{{object.payment.cheque.bank}}">
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="">Account Number:</label>
		              <input class="form-control" type="text" id="" disabled value="{{object.payment.cheque.account_number}}">
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="">Cheque Number:</label>
		              <input class="form-control" type="text" id="" disabled value="{{object.payment.cheque.cheque_number}}">
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="">Cheque Date:</label>
		              <input class="form-control" type="text" id="" disabled value="{{object.payment.cheque.cheque_date}}">
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="">Amount On Cheque:</label>
		              <input class="form-control" type="text" id="" disabled value="{{object.payment.amount_paid|floatformat:2|intcomma}}">
			</div>
		</div>
		</div>
	</div>
	<div class="row">
	     <div class="col-md-6"></div> <!-- spacer-->
	     <div class="col-md-3"></div> <!-- spacer-->
	     <div class="col-md-3">
		   <input type="button" class="btn btn-primary btn-large" value="Make Payment" id=btn_make_payment>
	     </div>
	</div>
	<hr class="purchase_form_divider2">
	<form action="#" method="post" role="form">
		{%csrf_token%}
	<div id="payment_info">
		<div class="row">
		<div class="form-group col-md-4">
		      <label class="control-label" for="id_payment_option">Payment Option:</label>
			      {% render_field form.payment_option class+="form-control" %}
		</div>
		<div class="col-md-4"></div> <!-- spacer-->
		<div class="col-md-4"></div> <!-- spacer-->
		</div>
		<div class="row">
		<div id="cash_option">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_total_cash">Amount Paid:</label>
			      {% render_field form.total_cash class+="form-control" %}
			</div>
			<div class="col-md-5"></div> <!-- spacer-->
			<div class="col-md-4"></div> <!-- spacer-->
		</div>
		<div id="cheque_option">
			<div class="form-group col-md-4">
			      <label class="control-label" for="id_issuing_bank">Bank:</label>
			      {% render_field form.issuing_bank class+="form-control" %}
			      {% if form.issuing_bank.errors %}
			          {% for error in form.issuing_bank.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_issuing_bank").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_account_number">Account Number:</label>
			      {% render_field form.account_number class+="form-control" %}
			      {% if form.account_number.errors %}
			          {% for error in form.account_number.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_account_number").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_cheque_number">Cheque Number:</label>
			      {% render_field form.cheque_number class+="form-control" %}
			      {% if form.cheque_number.errors %}
			          {% for error in form.cheque_number.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_cheque_number").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_cheque_date">Cheque Date:</label>
			      {% render_field form.cheque_date class+="form-control datepicker" %}
			      {% if form.cheque_date.errors %}
			          {% for error in form.cheque_date.errors %}
				      <div class="alert-danger">{{error}}</div>
				  {% endfor%}
				  <script>$("#id_cheque_date").addClass("has-error")</script>
			      {% endif %}
			</div>
			<div class="form-group col-md-2">
			      <label class="control-label" for="id_amount_on_cheque">Amount On Cheque:</label>
			      {% render_field form.amount_on_cheque class+="form-control" %}
			</div>
		</div>
		</div>
		<div class=row>
		    <div class="col-md-4"></div> <!-- spacer-->
		    <div class="col-md-4"></div> <!-- spacer-->
		    <div class="col-md-4 padding-top-10">
			<button type=submit class="btn btn-primary btn-large">
				Submit Payment
			</button>
		    </div>
		</div>
	</div>
	</form>
       </div>
    </div>
</div>

<script type="text/javascript">
        $("#payment_info").hide();
	$("hr.purchase_form_divider2").hide();
	function get_total() {
	       var g_total;
	       g_total = 0.00;
	       $(".unit_total").each(function(index){
		      g_total = g_total + parseFloat($(this).html());
		      $(this).html($(this).html().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
		})
		return g_total;
	}

	$(document).ready(function(){
		var total = get_total();
		$("#gtotal").html(total.toFixed(2));
		$("#gtotal").html($("#gtotal").html().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
		var purchase_type = $("#id_purchase_type").val();
		var payment_status = "{{object.payment}}";
		if(payment_status == "None"){
	              $("#payment_info_display").hide();	
		      $("hr.purchase_form_divider").hide();
		}
		else  {
		      $("#btn_make_payment").hide();
	              $("#payment_info_display").show();	
		      $("hr.purchase_form_divider").show();
		}
                
		var payment_option = $("#id_payment_option_display").val();
		if(payment_option=="Cheque Payment"){
	              $("#cash_option_display").hide();	
	              $("#cheque_option_display").show();	
		}
		else {
	              $("#cheque_option_display").hide();	
	              $("#cash_option_display").show();	
		}

		$("#purchases-link").addClass("active");
		$("#purchase-all").addClass("active");
		$(".quantity-box").on("keyup paste input", function(){
		      var g_total = get_total();
		      $("#gtotal").html(g_total.toFixed(2));
		      $("#id_amount_on_cheque").val($("#gtotal").html());
		      $("#id_total_cash").val($("#gtotal").html());
		})

		$(function() {
			$(".datepicker").datepicker({
		            changeMonth: true,
		            changeYear: true,
		            dateFormat: "dd-mm-yy",
			    maxDate: '0'
			});
		});

		$("#id_purchase_type").change(function(){
		    var value = $(this).val();
		    if(value==0){
		        $("#payment_info").hide(300);    
			$("hr.purchase_form_divider").hide(300);
		    }

		    else{
		        $("#payment_info").show(300);
			$("hr.purchase_form_divider").show(300);
		    }
		})
		$("#id_payment_option").change(function(){
		    var value = $(this).val();
		    if(value==0){
		        $("#cash_option").hide(200);    
		        $("#cheque_option").show(200);    
		    }

		    else{
		        $("#cheque_option").hide(200);    
		        $("#cash_option").show(200);    
		    }
		})

		$("#btn_make_payment").click(function(){
	            $(this).hide();
		    $("hr.purchase_form_divider2").show();
		    $("#payment_info").show(200);
			var payment_option = $("#id_payment_option").val();
			if(payment_option==0){
			      $("#cash_option").hide();	
			      $("#cheque_option").show();	
			}
		else {
	              $("#cheque_option").hide();	
	              $("#cash_option").show();	
		}
		})

	})
</script>
{% endblock %}

templates/purchases/purchase_metrics.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% block subnav %}
{% include "purchases_subnav.html" %}
{% endblock %}
{% block contents %}
<div class="container main-contents">
    <div class="section">
	    <div class="section-header">
	          <p class="section-title">Purchases Metrics</p>
	    </div>
	    <div class="section-data">
		    <h1>Section is under development!</h1>
            </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#purchases-link").addClass("active");
		$("#purchase-metrics").addClass("active");
	})
</script>
{% endblock %}