agent/urls.py
from django.conf.urls import url
from django.views.generic import UpdateView
from views import *
from models import Vendor
from forms import VendorForm

urlpatterns = [
    url(r'^all/$', VendorListView.as_view(), name="all"),
    url(r'^all/json$', VendorJSONListView.as_view(), name="all-json"),
    url(r'^new/$', VendorCreate.as_view(), name="new"),
    url(r'^details/(?P<pk>\d+)/$', VendorDetailView.as_view(), name="detail"),
    url(r'^update/(?P<pk>\d+)/$', UpdateView.as_view(
        model=Vendor,
        form_class=VendorForm,
        template_name='agent/vendor_create_form.html',
        success_url='/vendors/all/'
        ), name="update"),
]

fanaider/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^vendors/', include('agent.urls', namespace='vendors')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

purchases/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^all/$', DayPurchaseListView.as_view(), name="all"),
    url(r'^damages/all/$', DamageCountListView.as_view(), name="damages-all"),
    url(r'^new/$', NewPurchaseView.as_view(), name="new"),
    url(r'^damages/new/$', NewDamageCountView.as_view(), name="damages-new"),
    url(r'^metrics/$', PurchaseMetricsView.as_view(), name="metrics"),
    url(r'^detail/(?P<pk>\d+)/$', DayPurchaseDetail.as_view(), name="detail"),
]

sales/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^bookings/all/$', AllBookingView.as_view(), name="bookings-all"),
    url(r'^bookings/add/$', NewBookingView.as_view(), name="add-booking"),
    url(r'^metrics/$', NewBookingView.as_view(), name="metrics"),
    url(r'^bookings/edit/(?P<pk>\d+)/$', BookingUpdateView.as_view(), name="edit"),
    url(r'^bookings/close/(?P<pk>\d+)/$', CloseBookingView.as_view(), name="close"),
    url(r'^bookings/pay/(?P<pk>\d+)/$', PayBookingView.as_view(), name="pay"),
    url(r'^bookings/view/(?P<pk>\d+)/$', BookingsDetailView.as_view(), name="view"),
]

templates/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Master Agent Platform</title>
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/formValidation.min.css' %}" rel="stylesheet">
      <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">
      <link href="https://cdn.datatables.net/fixedcolumns/3.2.2/css/fixedColumns.dataTables.min.css" rel="stylesheet">
      <link href="{% static 'css/custom.css' %}" rel="stylesheet">
      <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

		<script src="{% static 'js/jquery.min.js' %}"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery-ui.min.js' %}"></script>
		<script src="{% static 'js/formValidation.min.js' %}"></script>
		<script src="{% static 'js/framework/bootstrap.min.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
		<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/fixedcolumns/3.2.2/js/dataTables.fixedColumns.min.js"></script>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
          <body>
		  {% block banner %}
		  <div class="banner">
			  <img class=agent-logo src="/static/logo.png" alt="small logo">
				  <h2 id=agent_title>{{user.shopassistant.shop.agent.name}}{{user.agent.name}}</h2>
			  {% if user.is_authenticated %}
         		  <div class="user dropdown">
			  <a href="#" data-toggle="dropdown" class="dropdown-toggle" >
				  <span class="fa fa-user"> </span> {{user.get_full_name}}
				  <span class="caret"></span> 
			  </a>
			  <ul class="dropdown-menu">
				  <li><a href="{% url 'password_change'%}"><span class="fa fa-lock"></span> Change Password</a></li>
				  <li><a href="{% url 'logout' %}?next=/login/"><span class="fa fa-arrow-right">
						  </span> Logout</a>
				  </li>
			  </ul>
		  </div>

			  {% endif %}
		  </div>
		  {% endblock %}
		  {% block navbar %}
		  <div class="nav-bar">
			  <div class="nav-links-wrapper">
				  <ul class="nav-links">
					  <li class="nav-link"><a href="{% url 'sales:bookings-all'%}" id=sales-link>Sales</a></li>
					  <li class="nav-link"><a href="{% url 'purchases:all'%}" id=purchases-link>Purchases</a></li>
					  <li class="nav-link"><a href="{% url 'vendors:all'%}" id=vendors-link>Vendors</a></li>
					  <li class="nav-link"><a href="#" id=equipment-link>Equipment</a></li>
					  <li class="nav-link"><a href="{% url 'purchases:damages-all'%}" id=damages-link>Damages</a></li>
					  <li class="nav-link last-item"><a href="{% url 'purchases:damages-all'%}" id=promotions-link>Promotions</a></li>
				  </ul>
			  
			  </div>
		  </div>
		  {% endblock %}
		  {% block subnav %}

		  {% endblock %}
			  {% block contents %}
		  <div class="container">


			   <h1>This is the Base Template</h1>


			  {% endblock %}


			  {% block footer %}

			  {% endblock %}
		  </div>
		<script src="{% static 'js/customjs.js' %}"></script>
	  </body>
</html>

templates/damages_subnav.html
<div class="subnav">
	<div class="submenu">
		<a href="{% url 'purchases:damages-all'%}" class=submenu-item-link id=damages-all><span class="fa fa-th-list"></span> All Damages</a>
		<a href="{% url 'purchases:damages-new'%}" class=submenu-item-link id=damage-new><span class="fa fa-download"></span> New Damages</a>
	</div>
</div>

templates/footer.html
<div class=footer>
	<div class="row footer-contents">
	</div>
</div>

templates/purchases_subnav.html
<div class="subnav">
	<div class="submenu">
		<a href="{% url 'purchases:all'%}" class=submenu-item-link id=purchase-all><span class="fa fa-th-list"></span> All Purchases</a>
		<a href="{% url 'purchases:new'%}" class=submenu-item-link id=purchase-new><span class="fa fa-download"></span> New Purchase</a>
		<a href="{% url 'purchases:metrics'%}" class=submenu-item-link id=purchase-metrics><span class="fa fa-bar-chart"></span> Metrics</a>
	</div>
</div>

templates/sales_subnav.html
<div class="subnav">
	<div class="submenu">
		<a href="{% url 'sales:bookings-all'%}" class=submenu-item-link id=sales-bookings><span class="fa fa-th-list"></span> All Bookings</a>
		<a href="{% url 'sales:add-booking'%}" class=submenu-item-link id=add-bookings><span class="fa fa-edit"></span> New Booking</a>
		<a href="{% url 'sales:metrics'%}" class=submenu-item-link id=sales-metrics><span class="fa fa-bar-chart"></span> Metrics</a>
	</div>
</div>

templates/vendors_subnav.html
<div class="subnav">
	<div class="submenu">
		<a href="{% url 'vendors:all'%}" class=submenu-item-link id=vendor-all><span class="fa fa-th-list"></span> All Vendors</a>
		<a href="{% url 'vendors:new'%}" class=submenu-item-link id=vendor-new><span class="fa fa-user-plus"></span> Add Vendor</a>
	</div>
</div>